spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolibre?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver